# Generated by Django 6.0 on 2026-01-05 19:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the person contacting', max_length=100)),
                ('email', models.EmailField(help_text='Email address for response', max_length=254)),
                ('subject', models.CharField(help_text='Subject of the inquiry', max_length=200)),
                ('message', models.TextField(help_text='Message content')),
                ('status', models.CharField(choices=[('new', 'New'), ('read', 'Read'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('spam', 'Spam')], db_index=True, default='new', help_text='Current status of the inquiry', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the submitter', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Browser user agent string', null=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes by staff (not visible to user)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the message was submitted')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last time the message was updated')),
                ('replied_at', models.DateTimeField(blank=True, help_text='When the inquiry was replied to', null=True)),
                ('user', models.ForeignKey(blank=True, help_text='User who submitted the form (if authenticated)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='user_contac_created_5ed480_idx'), models.Index(fields=['status', '-created_at'], name='user_contac_status_c28134_idx'), models.Index(fields=['email'], name='user_contac_email_b6d6a0_idx')],
            },
        ),
    ]
