# Generated by Django 6.0 on 2026-01-03 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stocks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='baskets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='basketitem',
            name='basket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='stocks.basket'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['symbol'], name='stocks_stoc_symbol_3e1bfd_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['last_updated'], name='stocks_stoc_last_up_3b4825_idx'),
        ),
        migrations.AddField(
            model_name='basketitem',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.stock'),
        ),
        migrations.AddIndex(
            model_name='basket',
            index=models.Index(fields=['-created_at'], name='stocks_bask_created_b51930_idx'),
        ),
        migrations.AddIndex(
            model_name='basket',
            index=models.Index(fields=['updated_at'], name='stocks_bask_updated_fbbc12_idx'),
        ),
        migrations.AddIndex(
            model_name='basketitem',
            index=models.Index(fields=['basket', 'stock'], name='stocks_bask_basket__378968_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='basketitem',
            unique_together={('basket', 'stock')},
        ),
    ]
