# Generated by Django 6.0 on 2026-01-03 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='basket',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='symbol',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
        migrations.AddIndex(
            model_name='basket',
            index=models.Index(fields=['-created_at'], name='stocks_bask_created_b51930_idx'),
        ),
        migrations.AddIndex(
            model_name='basket',
            index=models.Index(fields=['updated_at'], name='stocks_bask_updated_fbbc12_idx'),
        ),
        migrations.AddIndex(
            model_name='basketitem',
            index=models.Index(fields=['basket', 'stock'], name='stocks_bask_basket__378968_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['symbol'], name='stocks_stoc_symbol_3e1bfd_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['last_updated'], name='stocks_stoc_last_up_3b4825_idx'),
        ),
    ]
