# Generated by Django 6.0 on 2026-01-04 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_chatgroup_chatgroupmember_chatmessage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatgroup',
            name='is_ai_only',
            field=models.BooleanField(default=False),
        ),
    ]
